# Generated by Django 5.2.13 on 2026-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admission_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
