# Generated by Django 5.2.13 on 2026-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admission_profile_pic_alter_admission_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
