# Generated by Django 5.2.13 on 2026-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
